#!/usr/bin/env python3

from lib.util import echo
from lib.game import Game

def print_internal(game):
    echo("History", game.history)
    for rule in game.player.rules:
        echo(rule)
        echo("Value", rule.value)
        echo("Weights", rule.get_weights())

def print_score(game):
    s = sum(1 for h in game.history if h[0]==h[1])
    echo("Total", len(game.history), s, s/len(game.history))

    s = sum(1 for h in game.history[-10:] if h[0]==h[1])
    echo("Last 10", s, s/len(game.history[-10:]))

def do_game(game, c, computer_choice):
    human_choice = int(c)
    assert (0 <= human_choice < game.space_size)
    game.player_collect(human_choice)
    echo(computer_choice)

def handle_invalid_input():
    echo("Invalid command")

def main():
    PS = "> "
    SPACE_SIZE = 10
    TOKENS = tuple(str(i) for i in range(SPACE_SIZE))
    game = Game(SPACE_SIZE)

    while True:
        computer_choice = game.player_pick()
        #echo("cheat", computer_choice)
        c = input(PS)
        if c in TOKENS: do_game(game, c, computer_choice)
        elif c == 's':  print_score(game)
        elif c == 'd':  print_internal(game)
        else:           handle_invalid_input()

main()
